angular.module('myApp', [
  'heading',
  'color',
  'shape',
  'gumball',
  'teaVarieties',
  'fisherman',
  'lumberJack',
  'ghost',
  'beard',
  'season',
  'haiku',
  'country',
  'accordionModule',
  // 'drag',
  'treasureTrolls',
  'docsTimeDirective',
  'communist',
  'drinkModule',
  'skittlesModule',
  'phoneModule',
  'gossipModule',
  'triviaModule',
  'squirtModule',
  'titleCase'
  ])